spring:
  application:
    name: HanaSecurities_Backend

  # Oracle 데이터베이스 설정 (환경변수 사용)
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@localhost:1521/FREEPDB1}
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${DB_USERNAME:system}
    password: ${DB_PASSWORD:dltkdgus482}
    hikari:
      connection-timeout: ${DB_CONNECTION_TIMEOUT:20000}
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      minimum-idle: ${DB_MIN_IDLE:5}
      idle-timeout: ${DB_IDLE_TIMEOUT:300000}
      max-lifetime: ${DB_MAX_LIFETIME:1800000}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

# API 토큰 설정
api:
  token:
    app-key: ${API_APP_KEY:your-app-key-here}
    app-secret: ${API_APP_SECRET:your-app-secret-here}
    base-url: ${API_BASE_URL:https://openapi.koreainvestment.com:9443}
    token-path: /oauth2/tokenP
    web-socket-token-path: /oauth2/Approval
    account-number: ${API_ACCOUNT_NUMBER:}
    account-product-code: ${API_ACCOUNT_PRODUCT_CODE:01}
    kiwoom-app-key: ${KIWOOM_APP_KEY:your-kiwoom-app-key-here}
    kiwoom-secret-key: ${KIWOOM_SECRET_KEY:your-kiwoom-secret-key-here}
    kiwoom-base-url: ${KIWOOM_API_BASE_URL:https://api.kiwoom.com}
    kiwoom-token-path: /oauth2/token
    naver-client-id: ${API_TOKEN_NAVER_CLIENT_ID:your-naver-client-id}
    naver-client-secret: ${API_TOKEN_NAVER_CLIENT_SECRET:your-naver-client-secret}


# 스케줄링 설정
spring.task.scheduling:
  pool:
    size: 2
  thread-name-prefix: scheduler-

# 로깅 설정
logging:
  level:
    com.hanati: DEBUG
    com.hanati.common.scheduler: INFO
    com.hanati.common.service: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/token-scheduler.log
    max-size: 10MB
    max-history: 30

# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true